### ISSUE TITLE
python3.7.10 pip failing

### ISSUE THREAD

**Issue by domanchi** [domanchi/devtools#2]
In the ansible refactor, we have the following code:

```yaml
- name: "Installing virtualenv"
  pip:
    name: virtualenv
    state: present
    executable: "{{ item }}"
  loop:
    # These should correspond to the Python versions installed
    - "{{ home_directory }}/.pyenv/versions/3.7.10/bin/pip"
    - "{{ home_directory }}/.pyenv/versions/3.8.9/bin/pip"
```

It seems to succeed (through ansible) for `3.8.9`, but not for `3.7.10`, failing with the following stack trace:

```
failed: [localhost] (item=/Users/domanchi/.pyenv/versions/3.7.10/bin/pip) => {
    "ansible_loop_var": "item",
    "changed": false,
    "cmd": [
        "/Users/domanchi/.pyenv/versions/3.7.10/bin/pip",
        "install",
        "virtualenv"
    ],
    "item": "/Users/domanchi/.pyenv/versions/3.7.10/bin/pip"
}

MSG:

:stderr: Traceback (most recent call last):
  File "/Users/domanchi/.pyenv/versions/3.7.10/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
```

However, similar to #1, it succeeds if done manually. I've tried adding:

```
environment:
  PYENV_ROOT: "{{ home_directory }}/.pyenv"
```

but still nada.

Interestingly, the source code for `3.8.9` and `3.7.10` `pip` is the same. Furthermore, it hard fails at this step since it can't even load the `pip` script to perform the check to see if `virtualenv` is installed.
